### ISSUE TITLE
Default English translation missing

### ISSUE THREAD

**Issue by vfonic** [CristiRazvi/enum_attributes_validation#11]
I just found this gem. It's exactly what I need! Thank you!

I have several models that have pretty-much the same enum.
I'd like to have a single error message for all of these enums.

Is it possible for me to add an entry like this to my `config/locales/en.yml`:

```yml
en:
  activerecord:
    errors:
      models:
        attributes:
          invalid_enum: "can't be %{value}. Valid values are: %{valid_values}"
```

I tried this and it doesn't work.

**Comment by CristiRazvi** [comment]
@vfonic sorry for the late response
currently it's not possibleto add a general error message for all the models

**Comment by kirillshamardin** [comment]
@vfonic @CristiRazvi 

It works fine:
```
en:
  errors:
    messages:
      invalid_enum: "can't be %{value}. Valid values are: %{valid_values}"
```
